name: festvialens
description: A test for my new app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  english_words: ^4.0.0
  provider: ^6.0.0
  carousel_slider: ^5.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  dio: ^5.7.0
  firebase_core: ^3.4.1
  firebase_analytics: ^11.3.1
  firebase_app_check: ^0.3.1+1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_ui_auth: ^1.15.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.3
  firebase_storage: ^12.3.0
  image_picker: ^1.1.2
  universal_html: ^2.0.9
  path: ^1.9.0
  dropdown_search: ^6.0.1
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true