import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_ui_auth/firebase_ui_auth.dart';

class ProfilePage extends StatelessWidget {
  
@override
  Widget build(BuildContext context) {
    return FutureBuilder<User?>(
      // Manages logins and logouts
      future: FirebaseAuth.instance.authStateChanges().first, 
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return Center(child: CircularProgressIndicator());
        }

        if (!snapshot.hasData || snapshot.data == null) {
          Future.microtask(() {
            // If not logged in, go to sin in page
            Navigator.of(context).pushReplacementNamed('/sign-in');
          });
          
        }
        // Shows profile screen generated by FirebaseUI
        return ProfileScreen(
          appBar: AppBar(
            iconTheme: IconThemeData(
              color: Theme.of(context).colorScheme.onSurface,
            ),
            title: Text(
              'Your Profile',
              style: TextStyle(
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
            centerTitle: true,
          ),
          actions: [
            // Error message if sign out button doesn't work
            SignedOutAction((context) {
              if (Navigator.of(context).canPop()) {
                Navigator.of(context).pop();
              } else {
                print('Cannot pop the screen');
              }
            }),
          ],
        
        );
      },
    );
  }
}
// End of Code